In [1]:
import torch

与其他python数组一样，张量也可以通过索引和切片来访问其中的元素。

如下所示，我们可以用 x[i-1] 来访问张量x的第i个元素

In [6]:
 x = torch.arange(12, dtype = torch.float32).reshape((3, 4))
 y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
 x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [10]:
(x[-1],
 x[1, -2],
 x[1: 2])

(tensor([ 8.,  9., 10., 11.]), tensor(6.), tensor([[4., 5., 6., 7.]]))

[除了读取，我们还可以通过索引来更改元素的值

In [12]:
x[1, 2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

如果我们想一次性将多个元素的值改为同一个值，可以使用切片操作，如下
这里的【0:2，表示选取第0行和第1行，：表示选取所有列

In [14]:
x[0:2, :] = 12

如果后续不需要用到x，我们就可以用以下两种方式来减少内存开销

In [16]:
x[:] = x + y
id(x)

2160225970672

In [17]:
x += y
id(x)

2160225970672