In [11]:
import torch

（1）通过适当复制元素来拓展较小的张量，使其形状与较大张量相同。

即使形状不同，我们也可以对张量进行按元素运算。这称为广播（broadcasting）。

（2）对生成的数组执行按元素运算。

大多数情况下我们将沿着数组中长度为1的轴进行广播。# # % % md

In [15]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

如下，a的左列复制到右列，b的上行复制到下行，然后再按元素相加

In [14]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])