标量：
标量由只有一个元素的张量表示。例如，一个包含单个数值的张量就是一个标量。

In [9]:
import torch

x = torch.tensor(3.5)
y = torch.tensor(2.5)
x + y, x - y, x * y, x / y, x**y

(tensor(6.), tensor(1.), tensor(8.7500), tensor(1.4000), tensor(22.9177))

<h3>向量</h3>
向量可以被视为标量值组成的列表，它们是只有一个轴（维度）的张量。

这些标量值被称为向量的元素或分量

当向量表示数据集中的样本时，它们的值有一定的实际意义。例如，一个包含3个元素的向量可以表示一个样本的3个特征值

再比方，如果我们训练一个模型来预测贷款违约风险，每个向量可能与一个申请人对应
向量的3个元素可以分别表示贷款金额、贷款期限和借款人的信用评分
而当向量表示模型的参数时，它们的值通常没有直接的实际意义，而是通过训练过程来调整，以便模型能够更好地拟合数据。

In [10]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

我们可以使用下表来引用向量的任一元素，
例如可以通过x[3]来获取第四个元素的值。
通常认为列向量是向量的默认方向。\

In [11]:
x [3]

tensor(3)

<h4>长度、形状和维度</h4>
向量的长度是指其包含的元素数量。在上面的例子中，向量x的长度为4，因为它包含4个元素。

向量的形状是一个元组，表示其在每个维度上的大小。在上面的例子中，向量x的形状为(4,)，表示它在唯一的维度上有4个元素。


与普通的python数组一样，我们可以通过调用len函数来获取向量的长度

当用张量表示一个向量是，我们也可以通过调用张量对象的shape属性来获取向量的形状

In [12]:
len(x), x.shape

(4, torch.Size([4]))

<H3>矩阵</H3>
矩阵是二维张量的一个特例。

正如向量将标量从0阶推广到1阶一样，矩阵将向量从1阶推广到2阶。

矩阵是一个二维数组，其中的元素可以通过两个索引来访问：行索引和列索引。

当调用函数实例化张量时，我们可以通过指定两个分量m和n来创建一个形状为m*n的矩阵

In [13]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

当我们交换矩阵的行和列时，就得到了矩阵的转置

In [14]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

<h3>高阶张量</h3>
高阶张量是指阶数大于2的张量。例如，三阶张量可以被视为一组矩阵的集合，其中每个矩阵都具有相同的形状。

 当我们开始处理图像时，张量将变得更加重要，图像通常表示为三阶张量，其中包含高度、宽度和颜色通道等维度。

In [15]:
x = torch.arange(24).reshape(2, 3, 4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])