In [1]:
import torch

In [2]:
x = torch.arange(12)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

通过张量的形状，我们可以知道它有多少个轴（维度）以及每个轴上有多少个元素。

In [4]:
x.shape

torch.Size([12])

想知道张量有多少个元素，可以使用 numel 方法

In [1]:
x.numel()

NameError: name 'x' is not defined

,这是因为处理的是单向量，所以他的形状和元素书相同。

如果我们想要一个矩阵，我们可以调整张量的形状。想要改变一个张量的形状而不改变其数据，可以使用 reshape 方法

In [10]:
x = x.reshape(3, 4)

In [11]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

好，我们先回复x的样子

In [13]:
x = x.reshape(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

通过指明一个维度的大小为-1，可以让PyTorch根据其他维度的大小推断出该维度的大小

In [15]:
y = x.reshape(2, -1, 3)
y

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

同样，我们有一些能够创建特定形状张量的函数。例如，下面的代码创建了一个3行4列的矩阵，矩阵中的所有元素都初始化为0

In [16]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

或者全都初始化为1

In [18]:
torch.ones (2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

或者随机

In [19]:
torch.randn(3, 4)

tensor([[ 1.1559,  1.5276,  0.5436, -1.2497],
        [-1.5996,  1.8596,  0.5866, -1.9833],
        [ 0.1859,  1.1660,  0.6595, -1.0484]])

In [20]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])